name: example
description: Example for the flutter_card_swiper

publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  bottom_bar: ^2.0.3
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.8.4
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.1.0
  heroicons: ^0.9.0
  http: ^1.1.0
  icon_decoration: ^2.0.0
  icons_plus: ^4.0.0
  ionicons: ^0.2.2
  path: ^1.8.3
  path_provider: ^2.1.0
  pie_chart: ^5.3.2
  sqflite: ^2.3.0
  swipe_cards: ^2.0.0+1
  swiping_card_deck: ^1.3.0

flutter:
  uses-material-design: true
